name: Hello world

on: #github action event type (push, pull_request 등등이 있음)
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: "context"
        env:
          COMMIT_ID: ${{github.sha}}
        run: echo "Commit id => $COMMIT_ID"
